//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sag.Data.Common.Query {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sag.Data.Common.Query._Resources", typeof(_Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 转换目标 的本地化字符串。
        /// </summary>
        internal static string DestTypeForConvert {
            get {
                return ResourceManager.GetString("DestTypeForConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标集合不允许为空！ 的本地化字符串。
        /// </summary>
        internal static string ExpectedMemberListNull {
            get {
                return ResourceManager.GetString("ExpectedMemberListNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 索引超出范围 的本地化字符串。
        /// </summary>
        internal static string IndexOutOfRange {
            get {
                return ResourceManager.GetString("IndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 “{0}” 不是类型 “{1}” 无法应用到集合。 的本地化字符串。
        /// </summary>
        internal static string InvalidObjectType {
            get {
                return ResourceManager.GetString("InvalidObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型{0}转换错误！ 的本地化字符串。
        /// </summary>
        internal static string InvalidTypeConvert {
            get {
                return ResourceManager.GetString("InvalidTypeConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数: “{0}”值错误 的本地化字符串。
        /// </summary>
        internal static string Invalidvalue {
            get {
                return ResourceManager.GetString("Invalidvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法转换Json:”{0}“到”{1}“。 的本地化字符串。
        /// </summary>
        internal static string JsonCannotConvertToType {
            get {
                return ResourceManager.GetString("JsonCannotConvertToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在Json反系列化集合节点过程发生了错误。 的本地化字符串。
        /// </summary>
        internal static string JsonDeserializeCollectionHasError {
            get {
                return ResourceManager.GetString("JsonDeserializeCollectionHasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Json令牌类型:“{0}” 不是属性名称。 的本地化字符串。
        /// </summary>
        internal static string JsonTokenTypeNotPropertyName {
            get {
                return ResourceManager.GetString("JsonTokenTypeNotPropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  “{0}” 不是类型 “{1}” 的定义 的本地化字符串。
        /// </summary>
        internal static string MemberNotDefinedForType {
            get {
                return ResourceManager.GetString("MemberNotDefinedForType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是Json数组开头界定。 的本地化字符串。
        /// </summary>
        internal static string NotJsonArrayStart {
            get {
                return ResourceManager.GetString("NotJsonArrayStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是Json对象开头界定。 的本地化字符串。
        /// </summary>
        internal static string NotJsonObjectStart {
            get {
                return ResourceManager.GetString("NotJsonObjectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未设置获取操作符枚举的函数委托.请先设置属性“{0}“。 的本地化字符串。
        /// </summary>
        internal static string NullGetOperatorWithStringDelegate {
            get {
                return ResourceManager.GetString("NullGetOperatorWithStringDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型参数 的本地化字符串。
        /// </summary>
        internal static string ParameterType {
            get {
                return ResourceManager.GetString("ParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性 ”{0}“ 没有读访问器 的本地化字符串。
        /// </summary>
        internal static string PropertyDoesNotHaveGetter {
            get {
                return ResourceManager.GetString("PropertyDoesNotHaveGetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 属性名称不能为空！ 的本地化字符串。
        /// </summary>
        internal static string PropertyNameCanotNull {
            get {
                return ResourceManager.GetString("PropertyNameCanotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ”{0}“ 类型不能为空！ 的本地化字符串。
        /// </summary>
        internal static string TypeCannotNull {
            get {
                return ResourceManager.GetString("TypeCannotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 ”{0}“ 包含泛型参数 的本地化字符串。
        /// </summary>
        internal static string TypeContainsGenericParameters {
            get {
                return ResourceManager.GetString("TypeContainsGenericParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 ”{0}“ 不可枚举 的本地化字符串。
        /// </summary>
        internal static string TypeNotIEnumerable {
            get {
                return ResourceManager.GetString("TypeNotIEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型参数不能为委托类型。 的本地化字符串。
        /// </summary>
        internal static string TypeParameterIsNotDelegate {
            get {
                return ResourceManager.GetString("TypeParameterIsNotDelegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ValueCannotNull {
            get {
                return ResourceManager.GetString("ValueCannotNull", resourceCulture);
            }
        }
    }
}
